CREATE TABLE HSL_Desfechos_4 (
  ID_PACIENTE VARCHAR(60) NOT NULL
, ID_ATENDIMENTO VARCHAR(60)
, DT_ATENDIMENTO VARCHAR(30)
, DE_TIPO_ATENDIMENTO VARCHAR(30)
, ID_CLINICA VARCHAR(100)
, DE_CLINICA VARCHAR(100)
, DT_DESFECHO VARCHAR(30)
, DE_DESFECHO VARCHAR(100)
);

-- ID_PACIENTE|ID_ATENDIMENTO|DT_ATENDIMENTO|DE_TIPO_ATENDIMENTO|ID_CLINICA|DE_CLINICA|DT_DESFECHO|DE_DESFECHO

CREATE INDEX IDX_HSL_Desfechos_4_1 ON HSL_Desfechos_4 (ID_PACIENTE);
CREATE INDEX IDX_HSL_Desfechos_4_2 ON HSL_Desfechos_4 (ID_ATENDIMENTO);

\copy HSL_Desfechos_4 
FROM '/Users/fbarbosa/git/repositoriodatasharingfapesp/arquivos-fonte/HSL_Junho2021-2020-06-30/HSL_Desfechos_4.csv' 
csv header delimiter '|'


