CREATE TABLE HSL_Exames_4 (
  ID_PACIENTE VARCHAR(60) NOT NULL
, ID_ATENDIMENTO VARCHAR(60)
, DT_COLETA VARCHAR(30)
, DE_ORIGEM VARCHAR(255)
, DE_EXAME VARCHAR(100)
, DE_ANALITO VARCHAR(100)
, DE_RESULTADO TEXT
, CD_UNIDADE VARCHAR(100)
, DE_VALOR_REFERENCIA TEXT
);

CREATE INDEX IDX_HSL_Exames_4_1 ON HSL_Exames_4 (ID_PACIENTE);

\copy HSL_Exames_4 
FROM '/Users/fbarbosa/git/repositoriodatasharingfapesp/arquivos-fonte/HSL_Junho2021-2020-06-30/HSL_Exames_4.csv' 
csv header delimiter '|'


