CREATE TABLE EINSTEIN_Exames_2 (
  ID_PACIENTE VARCHAR(60) NOT NULL
, DT_COLETA VARCHAR(30)
, DE_ORIGEM VARCHAR(30)
, DE_EXAME VARCHAR(100)
, DE_ANALITO VARCHAR(100)
, DE_RESULTADO TEXT
, CD_UNIDADE VARCHAR(100)
, DE_VALOR_REFERENCIA VARCHAR(100)
);

CREATE INDEX IDX_EINSTEIN_Exames_2_1 ON EINSTEIN_Exames_2 (ID_PACIENTE);

--ID_PACIENTE|DT_COLETA|DE_ORIGEM|DE_EXAME|DE_ANALITO|DE_RESULTADO|CD_UNIDADE|DE_VALOR_REFERENCIA

\copy EINSTEIN_Exames_2 
FROM '/Users/fbarbosa/git/repositoriodatasharingfapesp/arquivos-fonte/EINSTEIN-Agosto-2020-06-30/EINSTEIN_Exames_2.csv' 
csv header delimiter '|'


