--
CREATE INDEX IDX_GrupoFleury_Exames_4_1 ON GrupoFleury_Exames_4 (ID_PACIENTE);

-- TOTAL DE LINHAS
-- 39567768 LINHAS DE DADOS IMPORTADAS
-- 39567768 LINHAS DE DADOS NO ARQUIVO
SELECT COUNT(*) qtd_n FROM GrupoFleury_Exames_4;

-- TOTAL DE LINHAS A SEREM CONSIDERADAS
-- REMOVENDO REGIAO "MMMM"
-- REMOVENDO AA_NASCIMENTO IGUAL "AAAA" 
-- REMOVENDO AA_NASCIMENTO IGUAL "YYYY"
-- TOTAL 38188574 LINHAS DE DADOS VÁLIDOS
select count(*) 
from GrupoFleury_Exames_4 e
join GrupoFleury_Pacientes_4 p ON (e.id_paciente = p.id_paciente)
where not cd_municipio ilike '%MMMM%'
  and AA_NASCIMENTO NOT IN ( 'AAAA', 'YYYY' );

-- QUANTIDADE DE EXAMES POR ANO
-- 2020=11175542
-- 2021=6388184
SELECT 
  SUBSTRING(E.DT_COLETA,7,4) AS ANO,
  COUNT(*) QTD_REGISTROS,
  COUNT(DISTINCT E.DE_EXAME || '*' || E.ID_ATENDIMENTO) QTD 
FROM GrupoFleury_Exames_4 E
JOIN GrupoFleury_Pacientes_4 P ON (e.id_paciente = p.id_paciente)
WHERE not P.cd_municipio ilike '%MMMM%'
  AND P.AA_NASCIMENTO NOT IN ( 'AAAA', 'YYYY' )
GROUP BY ANO
ORDER BY QTD DESC;

-- 
SELECT 
  DE_EXAME,
  COUNT(DISTINCT E.ID_ATENDIMENTO ) QTD_EXAMES,
  COUNT(DISTINCT E.DE_ANALITO) QTD_ANALITOS_DO_EXAME,
  COUNT(*) QTD
FROM GrupoFleury_Exames_4 E
JOIN GrupoFleury_Pacientes_4 P ON (e.id_paciente = p.id_paciente)
WHERE not P.cd_municipio ilike '%MMMM%'
  AND P.AA_NASCIMENTO NOT IN ( 'AAAA', 'YYYY' )
GROUP BY DE_EXAME
ORDER BY QTD DESC;