CREATE TABLE bpsp_exames_01 (
  ID_PACIENTE VARCHAR(60) NOT NULL
, ID_ATENDIMENTO VARCHAR(60) 
, DT_COLETA VARCHAR(30)
, DE_ORIGEM VARCHAR(30)
, DE_EXAME VARCHAR(100)
, DE_ANALITO VARCHAR(100)
, DE_RESULTADO TEXT
, CD_UNIDADE VARCHAR(100)
, DE_VALOR_REFERENCIA VARCHAR(100)
);

CREATE INDEX IDX_bpsp_exames_01_1 ON bpsp_exames_01 (ID_PACIENTE);

--ID_PACIENTE|ID_ATENDIMENTO|DT_COLETA|DE_ORIGEM|DE_EXAME|DE_ANALITO|DE_RESULTADO|CD_UNIDADE|DE_VALOR_REFERENCIA

\copy bpsp_exames_01 
FROM '/Users/fbarbosa/git/repositoriodatasharingfapesp/arquivos-fonte/BPSP-2021-04-28/bpsp_exames_01.csv' 
csv header delimiter '|'


