CREATE TABLE HC_PACIENTES_1 (
  ID_PACIENTE VARCHAR(60) NOT NULL PRIMARY KEY
, IC_SEXO VARCHAR(1) 
, AA_NASCIMENTO VARCHAR(4)
, CD_PAIS VARCHAR(2)
, CD_UF VARCHAR(2)
, CD_MUNICIPIO VARCHAR(255)
, CD_CEPREDUZIDO VARCHAR(8)
);
	

\copy HC_PACIENTES_1 
FROM '/Users/fbarbosa/git/repositoriodatasharingfapesp/arquivos-fonte/HC_Janeiro2021-2021-02-17/HC_PACIENTES_1.csv' 
csv header delimiter '|'