-- TOTAL DE LINHAS
-- 2952999 LINHAS DE DADOS IMPORTADAS
-- 2952999 LINHAS DE DADOS NO ARQUIVO
SELECT COUNT(*) qtd_n FROM HSL_Exames_4;

-- TOTAL DE LINHAS A SEREM CONSIDERADAS
-- REMOVENDO REGIAO "MMMM"
-- REMOVENDO AA_NASCIMENTO IGUAL "AAAA" 
-- REMOVENDO AA_NASCIMENTO IGUAL "YYYY"
-- TOTAL 1666190 LINHAS DE DADOS VÁLIDOS
select count(*) 
from HSL_Exames_4 e
join HSL_Pacientes_4 p ON (e.id_paciente = p.id_paciente)
where not cd_municipio ilike '%MMMM%'
  and AA_NASCIMENTO NOT IN ( 'AAAA', 'YYYY' );

-- QUANTIDADE DE EXAMES POR ANO
-- 2020=309366
-- 2021=206803
SELECT 
  SUBSTRING(E.DT_COLETA,7,4) AS ANO,
  COUNT(*) QTD_REGISTROS,
  COUNT(DISTINCT E.DE_EXAME || '*' || E.ID_PACIENTE || '*' || E.DT_COLETA) QTD 
FROM HSL_Exames_4 E
JOIN HSL_Pacientes_4 P ON (e.id_paciente = p.id_paciente)
WHERE not P.cd_municipio ilike '%MMMM%'
  AND P.AA_NASCIMENTO NOT IN ( 'AAAA', 'YYYY' )
GROUP BY ANO
ORDER BY QTD DESC;

-- 
-- 737 LINHAS
-- 38 ANALITOS NO HEMOGRAMA
SELECT 
  DE_EXAME,
  COUNT(DISTINCT E.ID_PACIENTE || '*' || E.DT_COLETA ) QTD_EXAMES,
  COUNT(DISTINCT E.DE_ANALITO) QTD_ANALITOS_DO_EXAME,
  COUNT(*) QTD
FROM HSL_Exames_4 E
JOIN HSL_Pacientes_4 P ON (e.id_paciente = p.id_paciente)
WHERE not P.cd_municipio ilike '%MMMM%'
  AND P.AA_NASCIMENTO NOT IN ( 'AAAA', 'YYYY' )
GROUP BY DE_EXAME
ORDER BY QTD DESC;