CREATE TABLE GrupoFleury_Exames_4 (
  ID_PACIENTE VARCHAR(60) NOT NULL
, ID_ATENDIMENTO VARCHAR(60) 
, DT_COLETA VARCHAR(30)
, DE_ORIGEM VARCHAR(30)
, DE_EXAME VARCHAR(100)
, DE_ANALITO VARCHAR(100)
, DE_RESULTADO VARCHAR(1500)
, CD_UNIDADE VARCHAR(100)
, DE_VALOR_REFERENCIA VARCHAR(100)
);

CREATE INDEX IDX_GrupoFleury_Exames_4_1 ON GrupoFleury_Exames_4 (ID_PACIENTE);

--ID_PACIENTE|ID_ATENDIMENTO|DT_COLETA|DE_ORIGEM|DE_EXAME|DE_ANALITO|DE_RESULTADO|CD_UNIDADE|DE_VALOR_REFERENCIA

\copy GrupoFleury_Exames_4 
FROM '/Users/fbarbosa/git/repositoriodatasharingfapesp/arquivos-fonte/GrupoFleury_Junho2021/GrupoFleury_Exames_4.csv' 
csv header delimiter '|'


