-- TOTAL DE LINHAS
-- 3415155 LINHAS DE DADOS IMPORTADAS
-- 3415155 LINHAS DE DADOS NO ARQUIVO
SELECT COUNT(*) qtd_n FROM EINSTEIN_Exames_2;

-- TOTAL DE LINHAS A SEREM CONSIDERADAS
-- REMOVENDO REGIAO "MMMM"
-- REMOVENDO AA_NASCIMENTO IGUAL "AAAA" 
-- REMOVENDO AA_NASCIMENTO IGUAL "YYYY"
-- TOTAL 2712261 LINHAS DE DADOS VÁLIDOS
select count(*) 
from EINSTEIN_Exames_2 e
join EINSTEIN_Pacientes_2 p ON (e.id_paciente = p.id_paciente)
where not cd_municipio ilike '%MMMM%'
  and AA_NASCIMENTO NOT IN ( 'AAAA', 'YYYY' );

-- QUANTIDADE DE EXAMES POR ANO
-- 2019=81217
-- 2020=662956
SELECT 
  SUBSTRING(E.DT_COLETA,7,4) AS ANO,
  COUNT(*) QTD_REGISTROS,
  COUNT(DISTINCT E.DE_EXAME || '*' || E.ID_PACIENTE || '*' || E.DT_COLETA) QTD 
FROM EINSTEIN_Exames_2 E
JOIN EINSTEIN_Pacientes_2 P ON (e.id_paciente = p.id_paciente)
WHERE not P.cd_municipio ilike '%MMMM%'
  AND P.AA_NASCIMENTO NOT IN ( 'AAAA', 'YYYY' )
GROUP BY ANO
ORDER BY QTD DESC;

-- 
-- 61 LINHAS
SELECT 
  DE_EXAME,
  COUNT(DISTINCT E.ID_PACIENTE || '*' || E.DT_COLETA ) QTD_EXAMES,
  COUNT(DISTINCT E.DE_ANALITO) QTD_ANALITOS_DO_EXAME,
  COUNT(*) QTD
FROM EINSTEIN_Exames_2 E
JOIN EINSTEIN_Pacientes_2 P ON (e.id_paciente = p.id_paciente)
WHERE not P.cd_municipio ilike '%MMMM%'
  AND P.AA_NASCIMENTO NOT IN ( 'AAAA', 'YYYY' )
GROUP BY DE_EXAME
ORDER BY QTD DESC;