-- CRIANDO TABELA PARA CONSOLIDAÇÃO DE EXAMES (UNIFICAÇÃO)
CREATE TABLE EXAMES (
  ID_PACIENTE VARCHAR(60) NOT NULL
, ID_ATENDIMENTO VARCHAR(60)
, DT_COLETA VARCHAR(30)
, DE_ORIGEM VARCHAR(255)
, DE_EXAME VARCHAR(100)
, DE_ANALITO VARCHAR(100)
, DE_RESULTADO TEXT
, CD_UNIDADE VARCHAR(100)
, DE_VALOR_REFERENCIA TEXT
, TABELA_ORIGEM VARCHAR(60) 
, DATA_CRIACAO TIMESTAMP
);

CREATE INDEX IDX_EXAMES_1 ON EXAMES (ID_PACIENTE);
CREATE INDEX IDX_EXAMES_2 ON EXAMES (DT_COLETA);


-- ADICIONANDO REGISTROS DE EXAMES DAS ORGANIZAÇÕES DE SAÚDE COM A EXCEÇÃO DO GRUPO FLEURY (-grupofleury_exames_4)
-- 6948473 LINHAS ADICIONADAS
INSERT INTO EXAMES (ID_PACIENTE, ID_ATENDIMENTO, DT_COLETA, DE_ORIGEM, DE_EXAME, DE_ANALITO, DE_RESULTADO, CD_UNIDADE, DE_VALOR_REFERENCIA, TABELA_ORIGEM, DATA_CRIACAO)
  SELECT e.ID_PACIENTE, ID_ATENDIMENTO, DT_COLETA, DE_ORIGEM, DE_EXAME, DE_ANALITO, DE_RESULTADO, CD_UNIDADE, DE_VALOR_REFERENCIA, 'bpsp_exames_01', CURRENT_TIMESTAMP 
  FROM bpsp_exames_01 E JOIN bpsp_pacientes_01 P ON (E.ID_PACIENTE=P.ID_PACIENTE) 
  WHERE not p.cd_municipio ilike '%MMMM%' and p.AA_NASCIMENTO NOT IN ( 'AAAA', 'YYYY' )
  UNION ALL
  SELECT e.ID_PACIENTE, NULL, DT_COLETA, DE_ORIGEM, DE_EXAME, DE_ANALITO, DE_RESULTADO, CD_UNIDADE, DE_VALOR_REFERENCIA, 'einstein_exames_2', CURRENT_TIMESTAMP 
  FROM einstein_exames_2 E
  JOIN einstein_pacientes_2 P ON (E.ID_PACIENTE=P.ID_PACIENTE) 
  WHERE not p.cd_municipio ilike '%MMMM%' and p.AA_NASCIMENTO NOT IN ( 'AAAA', 'YYYY' )
  UNION ALL
  SELECT e.ID_PACIENTE, ID_ATENDIMENTO, DT_COLETA, DE_ORIGEM, DE_EXAME, DE_ANALITO, DE_RESULTADO, CD_UNIDADE, DE_VALOR_REFERENCIA, 'hc_exames_1', CURRENT_TIMESTAMP 
  FROM hc_exames_1 E
  JOIN hc_pacientes_1 P ON (E.ID_PACIENTE=P.ID_PACIENTE) 
  WHERE not p.cd_municipio ilike '%MMMM%' and p.AA_NASCIMENTO NOT IN ( 'AAAA', 'YYYY' )
  UNION ALL
  SELECT e.ID_PACIENTE, ID_ATENDIMENTO, DT_COLETA, DE_ORIGEM, DE_EXAME, DE_ANALITO, DE_RESULTADO, CD_UNIDADE, DE_VALOR_REFERENCIA, 'hsl_exames_4', CURRENT_TIMESTAMP 
  FROM hsl_exames_4 E
  JOIN hsl_pacientes_4 P ON (E.ID_PACIENTE=P.ID_PACIENTE) 
  WHERE not p.cd_municipio ilike '%MMMM%' and p.AA_NASCIMENTO NOT IN ( 'AAAA', 'YYYY' );
  

-- ADICIONANDO REGISTROS DE EXAMES DO GRUPO FLEURY (+grupofleury_exames_4)
-- 38188574 LINHAS ADICIONADAS
INSERT INTO EXAMES (ID_PACIENTE, ID_ATENDIMENTO, DT_COLETA, DE_ORIGEM, DE_EXAME, DE_ANALITO, DE_RESULTADO, CD_UNIDADE, DE_VALOR_REFERENCIA, TABELA_ORIGEM, DATA_CRIACAO)
  SELECT E.ID_PACIENTE, ID_ATENDIMENTO, DT_COLETA, DE_ORIGEM, DE_EXAME, DE_ANALITO, DE_RESULTADO, CD_UNIDADE, DE_VALOR_REFERENCIA, 'grupofleury_exames_4', CURRENT_TIMESTAMP 
  FROM grupofleury_exames_4 E 
  JOIN grupofleury_pacientes_4 P ON (E.ID_PACIENTE=P.ID_PACIENTE) 
  WHERE not p.cd_municipio ilike '%MMMM%' and p.AA_NASCIMENTO NOT IN ( 'AAAA', 'YYYY' );


-- CONTANDO O NÚMERO DE REGISTRO DE CADA ORGANIZAÇÃO PARA COMPARAR COM TOTAL DE EXAMES
-- 45137047 LINHAS
SELECT SUM(U.QTD) SOMA_QTD_EXAMES FROM (
  SELECT COUNT(*) QTD 
  FROM bpsp_exames_01 E JOIN bpsp_pacientes_01 P ON (E.ID_PACIENTE=P.ID_PACIENTE) 
  WHERE not p.cd_municipio ilike '%MMMM%' and p.AA_NASCIMENTO NOT IN ( 'AAAA', 'YYYY' )
  UNION ALL
  SELECT COUNT(*) QTD
  FROM einstein_exames_2 E
  JOIN einstein_pacientes_2 P ON (E.ID_PACIENTE=P.ID_PACIENTE) 
  WHERE not p.cd_municipio ilike '%MMMM%' and p.AA_NASCIMENTO NOT IN ( 'AAAA', 'YYYY' )
  UNION ALL
  SELECT COUNT(*) QTD
  FROM hc_exames_1 E
  JOIN hc_pacientes_1 P ON (E.ID_PACIENTE=P.ID_PACIENTE) 
  WHERE not p.cd_municipio ilike '%MMMM%' and p.AA_NASCIMENTO NOT IN ( 'AAAA', 'YYYY' )
  UNION ALL
  SELECT COUNT(*) QTD
  FROM hsl_exames_4 E
  JOIN hsl_pacientes_4 P ON (E.ID_PACIENTE=P.ID_PACIENTE) 
  WHERE not p.cd_municipio ilike '%MMMM%' and p.AA_NASCIMENTO NOT IN ( 'AAAA', 'YYYY' )
  UNION ALL
  SELECT COUNT(*) QTD
  FROM grupofleury_exames_4 E 
  JOIN grupofleury_pacientes_4 P ON (E.ID_PACIENTE=P.ID_PACIENTE) 
  WHERE not p.cd_municipio ilike '%MMMM%' and p.AA_NASCIMENTO NOT IN ( 'AAAA', 'YYYY' )
) U;


-- CONTANDO O TOTAL DE EXAMES
-- 45137047 LINHAS
select count(*) from exames;