CREATE TABLE HC_EXAMES_1 (
  ID_PACIENTE VARCHAR(60) NOT NULL
, ID_ATENDIMENTO VARCHAR(60)
, DT_COLETA VARCHAR(30)
, DE_ORIGEM VARCHAR(30)
, DE_EXAME VARCHAR(100)
, DE_ANALITO VARCHAR(100)
, DE_RESULTADO TEXT
, CD_UNIDADE VARCHAR(100)
, DE_VALOR_REFERENCIA TEXT
);

CREATE INDEX IDX_HC_EXAMES_1_1 ON HC_EXAMES_1 (ID_PACIENTE);

\copy HC_EXAMES_1 
FROM '/Users/fbarbosa/git/repositoriodatasharingfapesp/arquivos-fonte/HC_Janeiro2021-2021-02-17/HC_EXAMES_1.csv' 
csv header delimiter '|'


